### ISSUE TITLE
import ait --> Error message

### ISSUE THREAD

**Issue by EinGuterWaran** [Lonami/autoit#6]
```
Traceback (most recent call last):
  File "post_on_instagram.py", line 5, in <module>
    import ait
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ait/__init__.py", line 3, in <module>
    from .ait import *
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ait/ait.py", line 57, in <module>
    from . import _linux as _mod
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ait/_linux.py", line 9, in <module>
    from .logger import Logger
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ait/logger.py", line 179, in <module>
    class KeyEvent:
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ait/logger.py", line 192, in KeyEvent
    for name in dir(Xlib.XK)
AttributeError: 'NoneType' object has no attribute 'XK'
```

**Comment by Lonami** [comment]
You need to install a few more things for this to work on Linux ([as documented in the README](https://github.com/Lonami/autoit#external-requirements)):

> Linux
> * xdotool to do any ait operation.
> * Python's Xlib to use ait.log (mouse/keyboard logger).
